### ISSUE TITLE
Any Updates?

### ISSUE THREAD

**Issue by seastar105** [joonb14/BlazePoseWithUnity#2]
does this project have only README?

**Comment by seastar105** [comment]
Sorry, I read your profile. It's demo only okay.

**Comment by joonb14** [comment]
Sorry, try contacting Tmax Metaverse if you need. \
email: [metaverse_sp@tmax.co.kr](https://www.tmaxmetaverse.com/)\
web: https://www.tmaxmetaverse.com/
